services:
  - type: web
    name: dracautobus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:5000 routes:app
    envVars:
      - key: FLASK_ENV
        value: production